server:
  port: ${SERVER_PORT:8080}

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ${MONGODB_LOCAL_URI:mongodb://root:verysecretlocalpassword@mongodb:27017/tvdash?authSource=admin}
minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:minio-server-local}
  port: ${MINIO_LOCAL_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:root}
  secret-key: ${MINIO_SECRET_KEY:verysecretlocalpassword}
  bucket: ${MINIO_BUCKET:tvdash}
  secure: ${MINIO_SECURE:false}

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${MONGODB_DEV_URI:mongodb://localhost:27016/tvdash}
minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:localhost}
  port: ${MINIO_LOCAL_PORT:9002}
  access-key: ${MINIO_ACCESS_KEY:neverdiscloseyoursecretsinconfigfiles}
  secret-key: ${MINIO_SECRET_KEY:neverdiscloseyoursecretsinconfigfiles}
  bucket: ${MINIO_BUCKET:tvdash}
  secure: ${MINIO_SECURE:false}

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_PROD_URI:mongodb://localhost:27017/tvdash}
minio:
  endpoint: ${MINIO_LOCAL_ENDPOINT:localhost}
  port: ${MINIO_LOCAL_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:neverdiscloseyoursecretsinconfigfiles}
  secret-key: ${MINIO_SECRET_KEY:neverdiscloseyoursecretsinconfigfiles}
  bucket: ${MINIO_BUCKET:tvdash}
  secure: ${MINIO_SECURE:true}